# exposed ports
ports:
- port: 8080
  onOpen: open-preview
# start up tasks
tasks:
- init: ./mvnw package -DskipTests
  command: java -jar target/*.jar
vscode:
  extensions:
    - microsoft.vscode-maven@0.21.2:myMavenPlugin====
